### ISSUE TITLE
Distributed binary files

### ISSUE THREAD

**Issue by ignatenkobrain** [DarkEld3r/os_info#145]
Hello,

I've noticed that now you ship some random binary files under lib folder. Could you not do that and somehow depend on win32 or something like that module?

**Comment by DarkEld3r** [comment]
To be clear: these are not random files, it is a `ntdll` library. These files were added quite long ago (#45). More details why these files are needed can be found [here](https://stackoverflow.com/questions/47744477/linking-ntdll-in-rust-application-using-cygwin-while-targeting-x86-64-pc-windows).

As far as I can see, it is the best way to get the actual version, because other functions from WinAPI are either deprecated or can return incorrect information in some cases. Though I'm not a Windows expert and would like to know if there is a better solution.

I suppose `GetProcAddress` can be used to obtain the address to this function. I'm going to try it.

**Comment by DarkEld3r** [comment]
I have published 2.0.1 version which includes fix for this issue.
