### ISSUE TITLE
Linker errors for 32-bit msvc builds

### ISSUE THREAD

**Issue by dherman** [DarkEld3r/os_info#87]
I've run into linker errors trying to use `os_info::get()` in 32-bit Windows (MSVC) builds. I wrote a minimal example that demonstrates the failure, and included an appveyor project so you can see the full output with the error.

Here's the [minimal example code](https://github.com/dherman/win-os-app), and here's the [Appveyor output](https://ci.appveyor.com/project/dherman/win-os-app).

Hope this is helpful!

**Comment by dherman** [comment]
For a bit more context, the linker error is failing to find `__imp__RtlGetVersion`. I'm a little bit baffled a) at the name mangling and b) that it can't find `RtlGetVersion` since the link command includes `ntdll.lib`, which is supposedly the library that contains that symbol. But I'm not an expert at Windows linking so I'm sort of stretching my limitations here. :)

**Comment by retep998** [comment]
The dllimport name mangling is not the issue. The issue is actually that the wrong calling convention is being used.

https://github.com/DarkEld3r/os_info/blob/4f7106f8729e169dfbe08027e9d93a6f083ba831/src/windows/winapi.rs#L35-L38

You want to be using `extern "system"` for Windows API functions, not `extern "C"`.
